name: Spellcasting
version: '1.0'
main: com.gotze.spellcasting.Spellcasting
api-version: '1.21.10'
depend: [ FastAsyncWorldEdit ]
permissions:
  spellcasting.admin:
    default: op
    children:
      command.admin: true
      command.pickaxe.clone: true
      command.pickaxe.debug: true
      command.pickaxe.repair: true
      command.pickaxe.reset: true